"""Начальная схема

Revision ID: 83d902745b60
Revises: 
Create Date: 2026-09-23 10:06:27.252113
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '83d902745b60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_dialogs',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('start_param', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('short_code', sa.String(length=8), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('colorblind_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('olympiads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('grades', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('official_url', sa.String(length=1024), nullable=True),
    sa.Column('organizers', sa.Text(), nullable=True),
    sa.Column('partner_universities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', 'subject_id', name='uq_olympiad_source_key'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('saved_olympiads',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('olympiad_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'olympiad_id')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olympiad_id', sa.Integer(), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('registration', 'qualifying', 'final', 'other', name='stage_kind'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('start_precision', sa.Enum('day', 'month', name='date_precision'), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('end_precision', sa.Enum('day', 'month', name='date_precision'), nullable=True),
    sa.Column('raw_date_range', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('olympiad_id', 'external_key', name='uq_stage_external_key')
    )
    op.create_index(op.f('ix_stages_ends_on'), 'stages', ['ends_on'], unique=False)
    op.create_index(op.f('ix_stages_olympiad_id'), 'stages', ['olympiad_id'], unique=False)
    op.create_index(op.f('ix_stages_starts_on'), 'stages', ['starts_on'], unique=False)
    op.create_table('stage_plans',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('planned_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stage_id')
    )
    op.create_index('ix_stage_plans_user_day', 'stage_plans', ['user_id', 'planned_on'], unique=False)
    op.create_table('stage_progress',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('passed', 'failed', name='stage_result'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_progress')
    op.drop_index('ix_stage_plans_user_day', table_name='stage_plans')
    op.drop_table('stage_plans')
    op.drop_index(op.f('ix_stages_starts_on'), table_name='stages')
    op.drop_index(op.f('ix_stages_olympiad_id'), table_name='stages')
    op.drop_index(op.f('ix_stages_ends_on'), table_name='stages')
    op.drop_table('stages')
    op.drop_table('saved_olympiads')
    op.drop_table('olympiads')
    op.drop_table('user_settings')
    op.drop_table('subjects')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('bot_dialogs')
    # ### end Alembic commands ###
