"""grade range

Revision ID: b9b2e5434691
Revises: 83d902745b60
Create Date: 2026-09-23 10:47:57.875300
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9b2e5434691'
down_revision: Union[str, None] = '83d902745b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olympiads', sa.Column('grade_min', sa.SmallInteger(), nullable=True))
    op.add_column('olympiads', sa.Column('grade_max', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('olympiads', 'grade_max')
    op.drop_column('olympiads', 'grade_min')
    # ### end Alembic commands ###
